<?php
/**
 * User: hotadmin
 * Date: 2024/2/23
 * Site: https://www.hotadmin.cn
 */


namespace app\index\controller;

use app\common\traits\AuthRuleTrait;
use app\common\traits\ConfigTrait;
use app\index\logic\Login as AuthLogic;
use app\index\traits\AuthTrait;
use think\App;
use think\facade\View;

class Base extends \app\common\controller\Base
{
    use AuthTrait;
    use ConfigTrait;
    use AuthRuleTrait;

    //在$this->checkLogin()中进行了初始化
    protected $user;

    protected $login;

    protected $config;

    /**
     * 无需登录的页面
     * @var array
     */
    protected $noNeedLogin = [];

    protected $noNeedRight = ['login', 'logout'];

    public function __construct(App $app)
    {
        parent::__construct($app);


        $this->login = AuthLogic::instance();
        $loginRes = $this->login->checkLogin($this->user);
        //登录验证
        if(!$this->login->noNeedLogin($this->noNeedLogin))
        {
            if(!$loginRes)
            {
                if(request()->action() !== 'login')
                    $this->redirect('login/login');
            }
        }
        //规则鉴权
        if(!$this->auth->needAuth($this->noNeedRight))
        {
            $uid = $this->user['id'] ?? 0;
            $this->checkAuth($uid);
        }

        //menus菜单
        $groupId = $this->user['group_id'] ?? 0;
        $menus = json_encode($this->getMenus('index', $groupId));
        //面包屑导航
        $breadCrumb = $this->getBreadCrumb("index");
        //前端设置
        $this->config = $this->getConfig("index");
        //halt($this->config);
        View::assign([
            'menus'=>$menus,
            'breadCrumb'=>$breadCrumb,
            'user'=>$this->user,
            'config'=>$this->config,
        ]);

        $this->initialize();
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub


    }

}