<?php

namespace app\index\controller;

use hotzhan\verify\sms\SmsVerifyCode;
use think\facade\View;

class Index extends Base
{
    protected $noNeedLogin = ['*'];
    protected $noNeedRight = ['*'];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return View::fetch();
    }

    public function contact()
    {
        return View::fetch();
    }

    public function token()
    {
        return token();
    }
}