<?php
/**
 * 后台应用控制器基类
 * User: hotadmin
 * Date: 2024/1/31
 * Site: https://www.hotadmin.cn
 */

namespace app\admin\controller;

use app\admin\controller\setting\Menu;
use app\admin\logic\Login as AuthLogic;
use app\admin\traits\BaseTrait;
use app\common\controller\Base as CommonBase;
use app\common\traits\AuthRuleTrait;
use app\common\traits\AuthTrait;
use app\common\traits\ConfigTrait;
use think\App;
use think\facade\Cache;
use think\facade\View;


class Base extends CommonBase
{
    use AuthTrait;
    use AuthRuleTrait;
    use ConfigTrait;

    //在$this->checkLogin()中进行了初始化
    protected $admin;

    protected $authLogin;

    protected $loginUrl = 'login/login';

    protected string $controller;
    protected string $action;

    protected $noNeedRight = ['login', 'logout', 'menus'];

    public function __construct(App $app)
    {
        parent::__construct($app);


        //单实例化对象
        $this->authLogin = AuthLogic::instance();

        //登录验证
        if(!$this->auth->needAuth($this->noNeedLogin))
        {
            if(!$this->authLogin->checkLogin($this->admin))
            {
                if(request()->action() !== 'login')
                    return $this->redirect('login/login');
            }
            else
            {
                $this->admin['is_pjax'] = $this->request->isPjax();
                //halt($this->admin);
            }

        }

        //规则鉴权
        if(!$this->auth->needAuth($this->noNeedRight))
        {
            $uid = $this->admin['id'] ?? 0;
            $this->checkAuth($uid);
        }

        //menus菜单，如果无缓存$menus=null，前端会用ajax重新获取，不能用缓存，无法使用规则了
        $groupId = $this->admin['group_id'] ?? 0;
        $menus = json_encode($this->getMenus('admin', $groupId));
        //标题
        $title = $this->getRuleName("admin");
        //面包屑导航
        $breadCrumb = $this->getBreadCrumb("admin");

        //网站信息
        $site = $this->getConfig('admin.base');

        //列表页每页显示条数
        $pagesize = cookie('pagesize') ?? 10;
        $pagesize = $pagesize > 100 ? 100 : $pagesize;
        $this->admin['pagesize'] = $pagesize;

        //渲染变量
        View::assign([
            'menus'=>$menus,//菜单
            'title'=>$title,//标题
            'breadCrumb'=>$breadCrumb,//面包屑导航
            'site'=>$site,//网站信息
            'pagesize'=>$pagesize,//列表页每页显示数量
        ]);

        $this->initialize();
    }

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub


    }

}