<?php
/**
 * User: hotadmin
 * Date: 2024/2/20
 * Site: https://www.hotadmin.cn
 */


namespace app\facade;



use think\Facade;

class Auth extends Facade
{
    protected static function getFacadeClass()
    {
        //parent::getFacadeClass(); // TODO: Change the autogenerated stub
        return 'hot\auth\Auth';
    }
}